---
- name: Install Helm
  hosts: VM
  remote_user: projet
  become: true

  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
        dest: /tmp/helm.tar.gz

    - name: Extract Helm archive
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: true
        creates: /tmp/linux-amd64/helm

    - name: Copy Helm binary to /usr/local/bin
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'

    - name: Verify Helm installation
      command: helm version
      register: helm_version_output
      changed_when: false

    - name: Display Helm version
      debug:
        var: helm_version_output.stdout_lines

